/g4sbs/usescint 0
/g4sbs/useckov 1

/g4sbs/DisableOpticalPhotonByMaterial BBHodo_Scinti
/g4sbs/DisableOpticalPhotonByMaterial Special_Air
/g4sbs/DisableOpticalPhotonByMaterial Mylar
/g4sbs/DisableOpticalPhotonByMaterial TF1
/g4sbs/DisableOpticalPhotonByMaterial F101
/g4sbs/DisableOpticalPhotonByMaterial TF5
/g4sbs/DisableOpticalPhotonByMaterial QuartzWindow_ECal
/g4sbs/DisableOpticalPhotonByMaterial Photocathode_BB
/g4sbs/DisableOpticalPhotonByMaterial Photocathode_material_ecal
/g4sbs/DisableOpticalPhotonByMaterial Pyrex_Glass
/g4sbs/DisableOpticalPhotonByMaterial CDET_BC408
/g4sbs/DisableOpticalPhotonByMaterial BCF_92
/g4sbs/DisableOpticalPhotonByMaterial CDET_Acrylic
/g4sbs/DisableOpticalPhotonByMaterial Photocathode_CDet
/g4sbs/DisableOpticalPhotonByMaterial EJ232
/g4sbs/DisableOpticalPhotonByMaterial BC484
/g4sbs/DisableOpticalPhotonByMaterial Glass_HC
/g4sbs/DisableOpticalPhotonByMaterial Paper
#/g4sbs/DisableOpticalPhotonByMaterial Air
#/g4sbs/DisableOpticalPhotonByMaterial RICH_air

## Configure G4SBS for gmn (Q^2 = 13.3 GeV^2)
#/g4sbs/filename        phi_SBS11_0.root   ## Output rootfile

## Configure Experiment
/g4sbs/exp             phi

## Configure the target
/g4sbs/target          LH2
/g4sbs/targlen         20.0 cm           ## Target Length
/g4sbs/rasterx 	       2.0 mm  #raster size in X
/g4sbs/rastery	       2.0 mm  #raster size in Y

/g4sbs/beamcur  60.0 muA

## Configure generator settings
#/g4sbs/kine            elastic           ## Generator
/g4sbs/kine 		pythia6
#/g4sbs/pythia6file      DeepPhi_0.root
/g4sbs/particle 	e-
/g4sbs/beamcur         1.0 muA
/g4sbs/beamE           11.00 GeV
/g4sbs/thmin           0.0 deg ## 15.0 deg
/g4sbs/thmax           180 deg ## 45.0 deg
/g4sbs/phmin           -180 deg ## -45 deg
/g4sbs/phmax           180 deg ## 45 deg

## Configure standard detector settings
/g4sbs/hcaldist        7.5 m
/g4sbs/hcalvoffset     -0.00 m
/g4sbs/beamlineconfig  4                 ## set relevant beamline configuration
/g4sbs/sbsclampopt     3                 ## Front field clamp only, was 3, 0 to remove, 

## Configure the magnets
/g4sbs/bbfield         1
#/g4sbs/scalebbfield    1.0776
/g4sbs/scalebbfield    0.9672 
#/g4sbs/tosfield        GMN13_field_newheader.table
#/g4sbs/sbsmagfield     0.97 tesla
#/g4sbs/tosfield  	BigBitePortableFieldMap.table 1
#/g4sbs/tosfield 	SBSPortableFieldMap_FrontClampOnly_NoPoleShims.table 2
/g4sbs/sbsmagfield     1.4 tesla  ## 1.23 tesla
/g4sbs/48d48field      1
/g4sbs/bbang           30.0 deg
/g4sbs/bbdist          1.55 m
/g4sbs/sbsang          14.0 deg
/g4sbs/48D48dist       2.25 m 

/g4sbs/uselead 0
/g4sbs/richdist    4.6 m
/g4sbs/richhoffset 0.025 m
/g4sbs/sbstrkrdist 5.925 m
/g4sbs/sbstrkrpitch 0.0 deg
/g4sbs/userichaero true
/g4sbs/richgas     C4F8
/g4sbs/grinchgas   C4F8

/g4sbs/keepsdtrackinfo 	all true
/g4sbs/totalabs true

## Run 100 events
/g4sbs/eventstatusevery 100

/g4sbs/uselead 	     0

#visualization stuff: turn off
# Use this open statement to create an OpenGL view:
#/vis/open OGLI 800x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
#/vis/viewer/set/autoRefresh false
#/vis/verbose errors
#
# Draw geometry:
#/vis/drawVolume worlds
#
# Set specific colour for identification : ghost parallel geometry envelope ("ghost") as yellow
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 90 89 deg
#
# Specify zoom value:
#/vis/viewer/zoom 2.5
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
#/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add neutron
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton white
#/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1. 0.2 1.0 1.0
#/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon+ 0.3 1.0 0.5 1.0
#/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon- 0.3 1.0 0.5 1.0
#
# To superimpose all of the events from a given run:
#/vis/scene/endOfEventAction accumulate 10000
#
# Re-establish auto refreshing and verbosity:
#/vis/viewer/set/autoRefresh true
#/vis/verbose warnings



#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#/g4sbs/run  100000
#/vis/geometry/set/visibility RICHbox_log -1 0

#/vis/geometry/set/forceWireframe b48d48Log -1 1
#/vis/geometry/set/forceWireframe FrontClamp_log -1 1

#/vis/viewer/flush
